@startuml UartSerial
' !include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/v1.0.1/theme.puml


hide empty members

' クラス図
set namespaceSeparator ::
namespace roblab{
    namespace common::serial{
        class Cobs{
            COBS変換クラス
        }
        class DataSerializer{
            シリアライズ（バイト列化）クラス
        }
        abstract class ISerialIO{
            シリアルIOインターフェース
        }
        
        class IdPacketManager{
            id付きパケット通信を管理するクラス
        }

        note left of IdPacketManager
        IdPacketManagerではデータの識別をid（番号）で行い
        MbedUartConnectionとPcUartConnectionでは
        tag（文字列）で行う
        end note

        note right of IdPacketManager
        Senderからデータを取り出して
        シリアライズ化を行う
        関数オブジェクトを保持
        end note

        class Sender{
            送信するデータをセットするクラス
        }
        class SerializeTypeInfo{
            シリアライズ化するデータの型情報を保持するクラス
        }

        class ByteRingBuffer{
            バイト列をリングバッファで管理するクラス
            クラス間のバイト列のやり取りには基本的にこれを使用
        }


        IdPacketManager ..> Sender : <<create>>
        IdPacketManager ..> Sender : 送るデータを取得
        IdPacketManager ..> DataSerializer : <<use>>
        IdPacketManager ..> Cobs : <<use>>
        ISerialIO --o IdPacketManager

        DataSerializer ..> SerializeTypeInfo : <<use>>
    }

    namespace mbed::serial{
        class PcUartConnection{
            PCとのUART通信を管理するクラス
        }
        class MbedUartSerialIo{
            UARTシリアルIO
        }
    }

    namespace ros::serial{
        class MbedUartConnection {
            mbedとのUART通信を管理するクラス
        }

        note left of MbedUartConnection 
        Sender作成情報とReceiveCb登録情報を
        関数オブジェクトとして保持し
        リクエストされてIDが判明したタイミングで
        対応するidでIdPacketManagerに登録する
        end note

        class UbuntuUartIO{
            UARTシリアルIO
        }
    }
    ros::serial::UbuntuUartIO <|.. common::serial::ISerialIO
    mbed::serial::MbedUartSerialIo <|.. common::serial::ISerialIO
    
    ros::serial::MbedUartConnection  o-- common::serial::IdPacketManager
    mbed::serial::PcUartConnection o-- common::serial::IdPacketManager
}

@enduml