name: Daily Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_docs:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SSH setting
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALPS_DOCS_SSH_PRIVATE_KEY }}
          ALPS_COMMON_LIB_DEPLOY_KEY: ${{ secrets.ALPS_COMMON_LIB_DEPLOY_KEY }}
          ALPS_LINUX_LIB_DEPLOY_KEY: ${{ secrets.ALPS_LINUX_LIB_DEPLOY_KEY }}
          ALPS_ROS_LIB_DEPLOY_KEY: ${{ secrets.ALPS_ROS_LIB_DEPLOY_KEY }}
          ALPS_ROS2_LIB_DEPLOY_KEY: ${{ secrets.ALPS_ROS2_LIB_DEPLOY_KEY }}
          ALPS_MBED_LIB_DEPLOY_KEY: ${{ secrets.ALPS_MBED_LIB_DEPLOY_KEY }}
          ALPS_STM32_LIB_DEPLOY_KEY: ${{ secrets.ALPS_STM32_LIB_DEPLOY_KEY }}
        run: |
          mkdir -p /home/runner/.ssh/
          echo -e "$SSH_PRIVATE_KEY" > /home/runner/.ssh/id_rsa
          echo -e "$ALPS_COMMON_LIB_DEPLOY_KEY" > /home/runner/.ssh/id_rsa_common_lib
          echo -e "$ALPS_LINUX_LIB_DEPLOY_KEY" > /home/runner/.ssh/id_rsa_linux_lib
          echo -e "$ALPS_ROS_LIB_DEPLOY_KEY" > /home/runner/.ssh/id_rsa_ros_lib
          echo -e "$ALPS_ROS2_LIB_DEPLOY_KEY" > /home/runner/.ssh/id_rsa_ros2_lib
          echo -e "$ALPS_MBED_LIB_DEPLOY_KEY" > /home/runner/.ssh/id_rsa_mbed_lib
          echo -e "$ALPS_STM32_LIB_DEPLOY_KEY" > /home/runner/.ssh/id_rsa_stm32_lib
          chmod 600 /home/runner/.ssh/id_rsa*

      - name: Checkout submodule
        run: |
          git submodule init doxygen-awesome-css
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa_common_lib"
          git submodule update --init --remote alps_common_lib
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa_linux_lib"
          git submodule update --init --remote alps_linux_lib
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa_ros_lib"
          git submodule update --init --remote alps_ros_lib
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa_ros2_lib"
          git submodule update --init --remote alps_ros2_lib
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa_mbed_lib"
          git submodule update --init --remote alps_mbed_lib
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa_stm32_lib"
          git submodule update --init --remote alps_stm32_lib

      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install doxygen
        run: |
          sudo apt-get install -y doxygen
          doxygen --version
          
      - name: Generate documentation
        run: |
          git checkout main
          doxygen Doxyfile
          git add .
          git commit -m "Generated documentation"

      - name: Push main branch
        run: |
          git push origin main

      - name: Deploy documentation
        run: |
          git checkout gh-pages
          git checkout main docs/
          git add .
          git commit -m "Update documentation"
          git push origin gh-pages

          git checkout main
          echo "Documentation generation and deployment completed."

