# 毎日0時にドキュメントを自動更新するワークフロー
name: Daily Update

on:
  # 毎日0時に実行．手動で実行することも可能．
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_docs:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      # リポジトリをチェックアウト(すべてのブランチを取得）
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          submodules: recursive

      # alps_coreを最新に更新
      - name: Update alps_core
        run: |
          git submodule update --remote alps_core

      # Gitのユーザー設定
      - name: Git user config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 必要なパッケージのインストール
      - name: Install doxygen and graphviz
        run: |
          sudo apt-get install -y doxygen
          sudo apt-get install -y graphviz
          
      # ドキュメントの生成
      - name: Generate documentation
        run: |
          doxygen Doxyfile

      # 生成したドキュメントに変更点がなければ終了．あればコミットしてプッシュ．
      - name: Commit and Push
        run: |
          if git diff --quiet; then
            echo "nothing to commit"
            exit 0
          fi

          git add .
          git commit -m "ドキュメントが自動生成されました"
          git push origin main

      # gh-pagesブランチに切り替えてdocsディレクトリをmainからコピー
      - name: Update gh-pages
        run: |
          git checkout gh-pages
          git checkout main docs/

          if git diff --quiet; then
            echo "nothing to commit"
            exit 0
          fi

          git add .
          git commit -m "ドキュメントが自動更新されました"
          git push origin gh-pages
