name: Daily Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_docs:
    runs-on: ubuntu-latest
    steps:
      # - name: SSH Setting
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.ALPS_DOCS_SSH_PRIVATE_KEY }}
      #   run: |
      #     mkdir -p /home/runner/.ssh/
      #     echo -e "$SSH_PRIVATE_KEY" > /home/runner/.ssh/id_rsa
      #     chmod 600 /home/runner/.ssh/id_rsa

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.ALPS_DOCS_SSH_PRIVATE_KEY }}
          submodules: recursive

      # - name: Checkout Submodule
      #   run: |
      #     git submodule update --init --recursive

      - name: git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: install doxygen
        run: |
          sudo apt-get install -y doxygen
          doxygen --version
          
      - name: execute update script
        run: |
          ./update_docs.sh
